
[Array]$Apps = 
'*0trace*',
'*Abyss Web Server*',
'*ace-voip*',
'*aircrack-ng*',
'*amap*',
'*Angry IP Scanner*',
'*Apache2*',
'*apktool*',
'*Arcade Lines*',
'*armitage*',
'*asleap*',
'*autofs*',
'*automater*',
'*babylon*',
'*backdoor-factory*',
'*bbqsql*',
'*bdfproxy*',
'*bed*',
'*beef-xss*',
'*BitTornado*',
'*BitTorrent*',
'*blindelephant*',
'*bluelog*',
'*blueranger*',
'*bluesnarfer*',
'*bulk-extractor*',
'*bully*',
'*burpsuite*',
'*Cain and Abel*',
'*ccleaner*',
'*cdpsnarf*',
'*cewl*',
'*cherrytree*',
'*Chicken Invaders*',
'*chirp*',
'*chromium*',
'*cisco-auditing-tool*',
'*cisco-global-exploiter*',
'*cisco-ocs*',
'*cisco-torch*',
'*clusterd*',
'*cmospwd*',
'*commix*',
'*copy-router-config*',
'*cowpatty*',
'*creddump*',
'*crunch*',
'*cryptcat*',
'*cryptsetup-bin*',
'*cryptsetup-initramfs*',
'*cryptsetup-run*',
'*cryptsetup*',
'*cutycapt*',
'*cymothoa*',
'*davtest*',
'*dbd*',
'*ddrescue*',
'*deblaze*',
'*desktop-base*',
'*dex2jar*',
'*dirb*',
'*dirbuster*',
'*dmitry*',
'*dnmap*',
'*dnschef*',
'*dnsmap*',
'*dotdotpwn*',
'*dradis*',
'*driftnet*',
'*Driver Booster*',
'*Driver Support*',
'*Driver Update*',
'*dsniff*',
'*dumpzilla*',
'*eapmd5pass*',
'*edb-debugger*',
'*Endless Sky*',
'*enum4linux*',
'*enumiax*',
'*ettercap-common*',
'*ettercap-graphical*',
'*exe2hexbat*',
'*exploitdb*',
'*faraday*',
'*fcrackzip*',
'*fern-wifi-cracker*',
'*fierce*',
'*fiked*',
'*fimap*',
'*findmyhash*',
'*fragroute*',
'*fragrouter*',
'*framework2*',
'*Freeciv Kismet*',
'*ftester*',
'*Garden Planner*',
'*giskismet*',
'*gpp-decrypt*',
'*grabber*',
'*hamster-sidejack*',
'*hash-identifier*',
'*hashcat-utils*',
'*hashcat*',
'*hexinject*',
'*Home Web Server*',
'*hotpatch*',
'*httrack*',
'*hydra-gtk*',
'*hydra*',
'*hyperion*',
'*iaxflood*',
'*ike-scan*',
'*inetd*',
'*inetutils**',
'*init-system-helpers*',
'*init*',
'*intersect*',
'*intrace*',
'*inviteflood*',
'*irpas*',
'*Itunes*',
'*jad*',
'*javasnoop*',
'*jboss-autopwn*',
'*John the Ripper*',
'*john-data*',
'*john*',
'*johnny*',
'*joomscan*',
'*jsql-injection*',
'*killerbee*',
'*king-phisher*',
'*kismet-capture-common*',
'*kismet-capture-linux-bluetooth*',
'*kismet-capture-linux-wifi*',
'*kismet-capture-nrf-51822*',
'*kismet-capture-nrf-mousejack*',
'*kismet-capture-nxp-kw41z*',
'*kismet-capture-ti-cc-2531*',
'*kismet-capture-ti-cc-2540*',
'*kismet-core*',
'*kismet-logtools*',
'*kismet*',
'*KNCTR*',
'*Kodi*',
'*laudanum*',
'*Lazesoft*',
'*lbd*',
'*lcrack*',
'*logkeys*',
'*macchanger*',
'*maltego-teeth*',
'*maltego*',
'*mdk3*',
'*medusa*',
'*metasploit-framework*',
'*mfoc*',
'*mfterm*',
'*mimikatz*',
'*miranda*',
'*mitmproxy*',
'*msfpc*',
'*multimac*',
'*nautilus-extension-gnome-terminal*',
'*nbtscan*',
'*ncat-w32*',
'*ncat*',
'*ncrack*',
'*ndiff*',
'*NetBus Pro*',
'*netcat-openbsd*',
'*netcat*',
'*netdiscover*',
'*netsniff-ng*',
'*nfs-common*',
'*nfs-kernel-server*',
'*nfspy*',
'*nginx-common*',
'*nginx*',
'*Nginx*',
'*nikto*',
'*nipper-ng*',
'*nishang*',
'*nmap-common*',
'*nmap*',
'*Nmap*',
'*ohrwurm*',
'*ollydbg*',
'*Open TFTP server*',
'*openbsd-inetd*',
'*ophcrack-cli*',
'*ophcrack*',
'*Ophcrack*',
'*oscanner*',
'*p0f*',
'*pack*',
'*padbuster*',
'*paros*',
'*patator*',
'*pdf-parser*',
'*pdfcrack*',
'*pdfid*',
'*pdgmail*',
'*perl-cisco-copyconfig*',
'*pipal*',
'*pixiewps*',
'*plecost*',
'*pnetcat*',
'*portmap*',
'*Postgresql*',
'*powerfuzzer*',
'*powersploit*',
'*protos-sip*',
'*pure-ftpd*',
'*pwnat*',
'*pyrit*',
'*Radmin Server*',
'*rainbowcrack*',
'*Rainbowcrack*',
'*rarcrack*',
'*rcracki-mt*',
'*Real Player*',
'*reaver*',
'*rebind*',
'*recon-ng*',
'*redfang*',
'*regripper*',
'*responder*',
'*Reveal Keylogger*',
'*rpcbind*',
'*rsmangler*',
'*rtpbreak*',
'*rtpflood*',
'*rtpinsertsound*',
'*rtpmixsound*',
'*sakis3g*',
'*sbd*',
'*scoket*',
'*sctpscan*',
'*set*',
'*sfuzz*',
'*sidguesser*',
'*siparmyknife*',
'*sipcrack*',
'*sipp*',
'*skipfish*',
'*smali*',
'*smtp-user-enum*',
'*sniffjoke*',
'*snmp*',
'*snmpcheck*',
'*socat*',
'*sock*',
'*sparta*',
'*spike*',
'*spooftooph*',
'*sqldict*',
'*sqlmap*',
'*sqlninja*',
'*sqlsus*',
'*sslcaudit*',
'*sslscan*',
'*sslsniff*',
'*sslstrip*',
'*sslyze*',
'*sucrack*',
'*tasksel-data*',
'*tasksel*',
'*tcpick*',
'*TeamViewer*',
'*termineter*',
'*tftpd32*',
'*thc-pptp-bruter*',
'*thc-ssl-dos*',
'*theharvester*',
'*tlssled*',
'*tnscmd10g*',
'*tracker-extract*',
'*tracker-miner-fs*',
'*tracker*',
'*truecrack*',
'*twofi*',
'*u3-pwn*',
'*ua-tester*',
'*unicorn-magic*',
'*unicornscan*',
'*uniscan*',
'*unix-privesc-check*',
'*urlcrazy*',
'*veil*',
'*vnc4server*',
'*vncsnapshot*',
'*voiphopper*',
'*volafox*',
'*vsftpd*',
'*vtgrab*',
'*wce*',
'*webacoo*',
'*webscarab*',
'*webshells*',
'*weevely*',
'*wfuzz*',
'*wifi-honey*',
'*wifitap*',
'*wifite*',
'*winexe*',
'*wireshark-common*',
'*wireshark-qt*',
'*wireshark*',
'*wordlists*',
'*wpscan*',
'*xinetd*',
'*xspy*',
'*xsser*',
'*zaproxy*',
'*zeitgeist*',
'*zenmap*'



ForEach ($App in $Apps) {

$data = get-package | sort-object Name | select-object name | Where-Object {$_.Name -like $App}


if($data){Write-Output "$($data.name)" | out-file ~\Desktop\programs2delete.txt -Append }

}


















